- name: Install MariaDB Server
  apt:
    name: mariadb-server
    state: present
    update_cache: true

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Install Python package for MySQL (PyMySQL)
  ansible.builtin.package:
    name: python3-pymysql
    state: present

- name: Create WordPress database
  mysql_db:
    name: wordpress
    state: present

- name: Create WordPress DB user
  mysql_user:
    name: wp_user
    password: wp_pass
    priv: 'wordpress.*:ALL'
    state: present
    host: '%'

