- name: Install MariaDB Server
  apt:
    name: mariadb-server
    state: present
    update_cache: true

- name: Start and enable MariaDB
  service:
    name: mariadb
    state: started
    enabled: true

- name: Install Python package for MySQL (PyMySQL)
  ansible.builtin.package:
    name: python3-pymysql
    state: present

- name: Create WordPress database
  community.mysql.mysql_db:
    name: wordpress
    state: present
    login_user: root
    login_password: yourpassword  # <-- make sure this matches the password you set in MySQL
    host: localhost

- name: Create WordPress DB user
  community.mysql.mysql_user:
    name: wpuser
    password: wpuserpassword
    priv: "wordpress.*:ALL"
    state: present
    login_user: root
    login_password: yourpassword  # <-- again, make sure this matches the root password
    host: localhost

