- name: Install Apache, PHP, and required packages
  apt:
    name:
      - apache2
      - php
      - php-mysql
      - libapache2-mod-php
      - unzip
    state: present
    update_cache: true

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip

- name: Unzip WordPress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /var/www/
    remote_src: yes

- name: Copy wp-config.php
  template:
    src: wp-config.php.j2
    dest: /var/www/wordpress/wp-config.php
    mode: '0644'

- name: Set proper permissions
  file:
    path: /var/www//wordpress
    recurse: yes
    owner: www-data
    group: www-data

- name: Restart Apache
  service:
    name: apache2
    state: restarted

