- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  loop:
    - apache2
    - php
    - php-mysql
    - libapache2-mod-php
    - wget
    - unzip
  become: yes

- name: Download WordPress
  get_url:
    url: https://wordpress.org/latest.zip
    dest: /tmp/wordpress.zip
  become: yes

- name: Unzip WordPress
  unarchive:
    src: /tmp/wordpress.zip
    dest: /var/www/html/
    remote_src: yes
  become: yes

- name: Set permissions
  file:
    path: /var/www/html/wordpress
    owner: www-data
    group: www-data
    state: directory
    recurse: yes
  become: yes

- name: Configure WordPress
  template:
    src: wp-config.php.j2
    dest: /var/www/html/wordpress/wp-config.php
  become: yes

- name: Restart Apache
  service:
    name: apache2
    state: restarted
  become: yes
